src/DAntE/app/models/dbbroker.py
import pandas as pd

from app import mongo


def parseData(data):
    df = pd.DataFrame()
    for e in data:
        new = pd.DataFrame(e['data'])
        df = df.append(new, ignore_index=True)

    return df

def insertRawData(collection, owner_id, project, df):
    df.reset_index(inplace=True)

    data = []
    for building_id in df['building_id'].unique():
        current = df[df['building_id'] == building_id]
        data.append({'owner_id': owner_id, 'project': project, 'building_id': int(building_id), 'data': current.to_dict('records')})

    return insert_many(collection, data)


def findRawData(collection, project, owner_id):
    data = list(find(collection, {'project': project, 'owner_id': owner_id}))

    df = parseData(data)    
    df.set_index('day', inplace=True)
    return df


def findPrototypes(collection, owner_id):
    data = list(find(collection, {'owner_id': owner_id}))

    df = parseData(data)
    return df


def replace(collection, filter, data):
    return mongo.db[collection].replace_one(filter, data, upsert=True)


def insert_one(collection, data):
    return mongo.db[collection].insert_one(data)


def find_one(collection, data):
    return mongo.db[collection].find_one(data)


def find(collection, data):
    return mongo.db[collection].find(data)


def insert_many(collection, data):
    return mongo.db[collection].insert_many(data)


def distinct(collection, dist, data):
    return mongo.db[collection].distinct(dist, data)

src/DAntE/app/models/user.py
import bcrypt

from app import mongo


class User:
    def __init__(self, email):
        self.email = email

    @staticmethod
    def is_authenticated():
        return True

    @staticmethod
    def is_active():
        return True

    @staticmethod
    def is_anonymous():
        return False

    def get_id(self):
        return self.email

    @staticmethod
    def check_password(password_hash, password):
        return bcrypt.hashpw(password.encode('utf-8'), password_hash) == password_hash

    @staticmethod
    def find_one(email):
        return mongo.db.Users.find_one({'email': email})

    @staticmethod
    def insert(email, password):
        return mongo.db.Users.insert({'email': email, 'password': password})

src/DAntE/app/__init__.py
import os

from flask import Flask, render_template
from flask_pymongo import PyMongo
from flask_login import LoginManager


mongo = PyMongo()
login_manager = LoginManager()


def create_app():
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object('config.DevConfig')

    mongo.init_app(app)
    login_manager.init_app(app)
    login_manager.login_view = 'auth_bp.login'
    login_manager.login_message_category = 'error'
    login_manager.refresh_view = 'auth_bp.login'
    login_manager.needs_refresh_message_category = 'error'

    with app.app_context():
        from . import routes
        from . import auth

        app.register_blueprint(auth.auth_bp)
        app.register_blueprint(routes.main_bp)

        from app.plotlydash.dash import create_dashboard
        app = create_dashboard(app)

        return app

src/DAntE/app/auth.py
import bcrypt

from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for
from flask_login import current_user, login_user, logout_user, fresh_login_required, login_required

from app import mongo, login_manager
from app.models.user import User


auth_bp = Blueprint('auth_bp', __name__, url_prefix='/auth')


@login_manager.user_loader
def load_user(email):
    user = User.find_one(email)
    if not user:
        return None
    return User(user['email'])

@auth_bp.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.index'))

    if request.method == 'POST':
        user = User.find_one(request.form['email'])
        if user and User.check_password(user['password'], request.form['password']):
            user_obj = User(user['email'])
            login_user(user_obj)
            return redirect(url_for('main_bp.index'))
        else:
            flash('Invalid email or password', category='error')
            return render_template('login.html')
    
    return render_template('login.html')

@auth_bp.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth_bp.login'))

@auth_bp.route('/signup', methods=['POST', 'GET'])
def signup():
    if request.method == 'POST':
        email = request.form['email']
        existing_user = User.find_one(email)

        if existing_user is None:
            hashpass = bcrypt.hashpw(request.form['password'].encode('utf-8'), bcrypt.gensalt())
            User.insert(email, hashpass)
            session['email'] = email

            return redirect(url_for('main_bp.index'))

        flash(email + ' is already registered!', category='error')
        return render_template('signup.html')

    return render_template('signup.html')

src/DAntE/app/routes.py
import os

from flask import Blueprint, redirect, current_app
from flask.helpers import send_from_directory


main_bp = Blueprint('main_bp', __name__)


@main_bp.route('/', methods=['GET'])
def index():
    return redirect('/dashboard/')

@main_bp.route('/download/<string:filename>', methods=['GET'])
def download_file(filename):
    data = os.path.join(current_app.root_path, current_app.config['DATA_DIR'])
    return send_from_directory(directory=data, filename=filename, as_attachment=True)

src/DAntE/app/templates/layout.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.0/lux/bootstrap.min.css" rel="stylesheet" integrity="sha384-smnSwzHqW1zKbeuSMsAM/fMQpkk7HY11LuHiwT8snL/W2QBoZtVCT4H5x1CEcJCs" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/layout.css') }}">

        <title>DAntE</title>
        <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/favicon.ico') }}">

        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    </head>

    <body>
        {% block layout %}{% endblock %}

        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    </body>
</html>

src/DAntE/app/templates/login.html
{% extends "layout.html" %}
{% block layout %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/login.css') }}">
<div class="col-lg text-center">
    <form class="form-signin" action="{{ url_for('auth_bp.login') }}" method="POST">
        <svg class="bi bi-lightning-fill" width="72" height="72" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
        </svg>
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label for="email" class="sr-only">Email</label>
        <input type="email" id="email" name="email" class="form-control" placeholder="Email address" required autofocus>
        <label for="password" class="sr-only">Password</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>

        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div id="flash" class="{{ category }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <br>
        <a href="{{ url_for('auth_bp.signup') }}">Not registered yet?</a>
        <br><br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
</div>
{% endblock %}

src/DAntE/app/templates/register.html
{% extends "layout.html" %}
{% block layout %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/login.css') }}">
<div class="col-lg text-center">
    <form class="form-signin" action="{{ url_for('auth_bp.register') }}" method="POST">
        <svg class="bi bi-lightning-fill" width="72" height="72" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
        </svg>
        <h1 class="h3 mb-3 font-weight-normal">Please sign up</h1>

        <div class="input-group">
            <div class="input-group-prepend">
                <span for="email" class="input-group-text">Email</span>
            </div>
            <input type="email" id="email" name="email" class="form-control" placeholder="admin@dante.com" required autofocus>
        </div>
        
        <br>

        <div class="input-group">
            <div class="input-group-prepend">
                <span for="password" class="input-group-text">Password</span>
            </div>
            <input type="password" id="password" name="password" class="form-control" required>
        </div>

        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="{{ category }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <br>
        <a href="{{ url_for('auth_bp.login') }}">Already registered?</a>
        <br><br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
    </form>
</div>
{% endblock %}

src/DAntE/app/templates/signup.html
{% extends "layout.html" %}
{% block layout %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/login.css') }}">
<div class="col-lg text-center">
    <form class="form-signin" action="{{ url_for('auth_bp.signup') }}" method="POST">
        <svg class="bi bi-lightning-fill" width="72" height="72" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
        </svg>
        <h1 class="h3 mb-3 font-weight-normal">Please sign up</h1>

        <div class="input-group">
            <div class="input-group-prepend">
                <span for="email" class="input-group-text">Email</span>
            </div>
            <input type="email" id="email" name="email" class="form-control" placeholder="admin@dante.com" required autofocus>
        </div>
        
        <br>

        <div class="input-group">
            <div class="input-group-prepend">
                <span for="password" class="input-group-text">Password</span>
            </div>
            <input type="password" id="password" name="password" class="form-control" required>
        </div>

        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div id="flash" class="{{ category }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <br>
        <a href="{{ url_for('auth_bp.login') }}">Already registered?</a>
        <br><br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
    </form>
</div>
{% endblock %}